### ISSUE TITLE
docsite panics when invalid links are present

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/docsite#19]
See https://buildkite.com/sourcegraph/sourcegraph/builds/39093#1772d252-e134-4531-92a5-aa90760eace0

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x12f1916]

goroutine 1 [running]:
net/http.(*ServeMux).ServeHTTP(0xc003c064c0, 0x1887940, 0xc003c06540, 0x0)
	/usr/local/go/src/net/http/server.go:2367 +0x26
github.com/sourcegraph/docsite.(*Site).checkContentPage.func2(0xc002b5b844, 0x3)
	/Users/nick/dev/gopath/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190303064655-ad3087aa6352/check.go:109 +0x188
github.com/sourcegraph/docsite.walkHTMLDocument(0xc002d591f0, 0xc0009bbc50)
	/Users/nick/dev/gopath/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190303064655-ad3087aa6352/check.go:156 +0x10d
github.com/sourcegraph/docsite.walkHTMLDocument(0xc002d59110, 0xc0009bbc50)
	/Users/nick/dev/gopath/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190303064655-ad3087aa6352/check.go:166 +0x5e
github.com/sourcegraph/docsite.walkHTMLDocument(0xc002d58d90, 0xc0009bbc50)
	/Users/nick/dev/gopath/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190303064655-ad3087aa6352/check.go:166 +0x5e
github.com/sourcegraph/docsite.walkHTMLDocument(0xc002d58310, 0xc0009bbc50)
	/Users/nick/dev/gopath/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190303064655-ad3087aa6352/check.go:166 +0x5e
github.com/sourcegraph/docsite.walkHTMLDocument(0xc002d356c0, 0xc0009bbc50)
	/Users/nick/dev/gopath/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190303064655-ad3087aa6352/check.go:166 +0x5e
github.com/sourcegraph/docsite.walkHTMLDocument(0xc002b6b7a0, 0xc0009bbc50)
	/Users/nick/dev/gopath/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190303064655-ad3087aa6352/check.go:166 +0x5e
github.com/sourcegraph/docsite.walkHTMLDocument(0xc002b6b030, 0xc0009bbc50)
	/Users/nick/dev/gopath/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190303064655-ad3087aa6352/check.go:166 +0x5e
github.com/sourcegraph/docsite.walkHTMLDocument(0xc002b6afc0, 0xc0009bbc50)
	/Users/nick/dev/gopath/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190303064655-ad3087aa6352/check.go:166 +0x5e
github.com/sourcegraph/docsite.(*Site).checkContentPage(0xc00044cf00, 0xc002d300c0, 0xc0033c5600, 0x11, 0x20)
	/Users/nick/dev/gopath/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190303064655-ad3087aa6352/check.go:115 +0x123
github.com/sourcegraph/docsite.(*Site).Check(0xc00044cf00, 0x1888900, 0xc0000b6000, 0x0, 0x0, 0x0, 0x100d3b9, 0x1d11dc0, 0x1eafd98, 0x0)
	/Users/nick/dev/gopath/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190303064655-ad3087aa6352/check.go:50 +0x704
main.init.0.func1(0xc0000b2010, 0x0, 0x0, 0x0, 0x0)
	/Users/nick/dev/gopath/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190303064655-ad3087aa6352/cmd/docsite/check.go:21 +0xb8
main.commander.run(0xc000228170, 0x2, 0x2, 0xc00036a120, 0x16e64e3, 0x7, 0xc00002f2c0, 0xc0000b2010, 0x1, 0x1)
	/Users/nick/dev/gopath/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190303064655-ad3087aa6352/cmd/docsite/cmd.go:117 +0x301
main.main()
	/Users/nick/dev/gopath/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190303064655-ad3087aa6352/cmd/docsite/main.go:46 +0xee

Errors found in Markdown documentation files. Fix the errors in doc/ and try again.
```

I deduced the problem and fixed with this commit:
https://github.com/sourcegraph/sourcegraph/pull/4769/commits/0f6184b813f37e327b0424807deafbb35824f26f

**Comment by unknwon** [comment]
I think this should have been resolved by saying the "Page not found". Please feel free to re-open if this is not the case.

Similar to https://github.com/sourcegraph/docsite/issues/84
